# Generated by Django 4.0.4 on 2022-06-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_date', models.DateField(blank=True, null=True, verbose_name='Appointment date')),
                ('timing', models.TimeField(blank=True, null=True, verbose_name='Timing')),
            ],
        ),
    ]
