# Generated by Django 4.0.4 on 2022-06-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed')], default='PENDING', max_length=15, null=True),
        ),
    ]
