# Generated by Django 4.0.4 on 2022-06-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientmore_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmore',
            name='appointment',
        ),
    ]
