# Generated by Django 4.0.4 on 2022-06-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('accounts', '0004_remove_patientmore_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormore',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospital.hospital'),
        ),
    ]
