# Generated by Django 4.0.4 on 2022-06-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, default='hospital/hospital.jpg', null=True, upload_to='hospital'),
        ),
    ]
