# Generated by Django 4.0.4 on 2022-06-19 05:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='overview',
            field=ckeditor.fields.RichTextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='services',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
