# Generated by Django 4.0.4 on 2022-06-19 05:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_overview_alter_hospital_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='overview',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='services',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
