# Generated by Django 4.0.4 on 2022-06-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospital_overview_alter_hospital_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
